version: '3.1'
services:

  aspsp-simulator:
    container_name: aspsp-simulator
    image: eu.gcr.io/openbanking-214714/securebanking/ob-aspsp-simulator:latest
    ports:
      - 8080:8080
    environment:
      - spring.data.mongodb.host=aspsp-mongo
    links:
      - aspsp-mongo

  aspsp-mongo:
    container_name: aspsp-mongo
    image: mongo:4.4.2
    ports:
      - 27017:27017
