aspsp:
  # TODO - what should this be? OB uses https://matls.rs.aspsp
  baseUrl: http://localhost:8080
  discovery:
    financialId: 0015800001041REAAY

#Swagger
springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs
